package com.atguigu.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-03-18T19:32:02.075+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "PhoneCheckImplService", 
                  wsdlLocation = "http://192.168.10.252:9999/phone?wsdl",
                  targetNamespace = "http://service.atguigu.com/") 
public class PhoneCheckImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.atguigu.com/", "PhoneCheckImplService");
    public final static QName PhoneCheckImplPort = new QName("http://service.atguigu.com/", "PhoneCheckImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.10.252:9999/phone?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PhoneCheckImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.10.252:9999/phone?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PhoneCheckImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PhoneCheckImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhoneCheckImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PhoneCheckImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PhoneCheckImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PhoneCheckImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PhoneCheck
     */
    @WebEndpoint(name = "PhoneCheckImplPort")
    public PhoneCheck getPhoneCheckImplPort() {
        return super.getPort(PhoneCheckImplPort, PhoneCheck.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhoneCheck
     */
    @WebEndpoint(name = "PhoneCheckImplPort")
    public PhoneCheck getPhoneCheckImplPort(WebServiceFeature... features) {
        return super.getPort(PhoneCheckImplPort, PhoneCheck.class, features);
    }

}
