package com.atguigu.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-03-18T19:32:01.924+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://service.atguigu.com/", name = "PhoneCheck")
@XmlSeeAlso({ObjectFactory.class})
public interface PhoneCheck {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkAreaByPhoneNum", targetNamespace = "http://service.atguigu.com/", className = "com.atguigu.service.CheckAreaByPhoneNum")
    @WebMethod
    @ResponseWrapper(localName = "checkAreaByPhoneNumResponse", targetNamespace = "http://service.atguigu.com/", className = "com.atguigu.service.CheckAreaByPhoneNumResponse")
    public java.lang.String checkAreaByPhoneNum(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkTypeByPhoneNum", targetNamespace = "http://service.atguigu.com/", className = "com.atguigu.service.CheckTypeByPhoneNum")
    @WebMethod
    @ResponseWrapper(localName = "checkTypeByPhoneNumResponse", targetNamespace = "http://service.atguigu.com/", className = "com.atguigu.service.CheckTypeByPhoneNumResponse")
    public java.lang.String checkTypeByPhoneNum(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
